"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



def lista_env(nombre):
    return [v.strip() for v in os.environ.get(nombre, "").split(",") if v.strip()]


# Sin variables de entorno = desarrollo (DEBUG, SQLite, canal en memoria).
# En producción (Docker) se configuran por entorno; ver .env.example.
# https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('Falta DJANGO_SECRET_KEY en producción.')
    SECRET_KEY = 'django-insecure-%2g!%#v*pqq1-4(vo7lhw*rhyy%=!)_151#pu#%9b#s=m!4sk6'

ALLOWED_HOSTS = lista_env('DJANGO_ALLOWED_HOSTS')
# Orígenes con esquema, p. ej. https://mgsimulator.com (necesario para formularios tras HTTPS/proxy).
CSRF_TRUSTED_ORIGINS = lista_env('DJANGO_CSRF_TRUSTED_ORIGINS')

# Railway publica la app por HTTPS en este dominio (p. ej. mgsim-production.up.railway.app).
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')


# Application definition

INSTALLED_APPS = [
    'daphne',  # primero: hace que runserver sirva ASGI (HTTP + WebSockets)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'managements',
    'user',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # sirve los estáticos en producción (sin nginx)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.invitaciones',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'
ASGI_APPLICATION = 'main.asgi.application'

# Con REDIS_URL (producción) los avisos por WebSocket pasan por Redis y funcionan con varios
# procesos o servidores; sin ella, capa en memoria (un solo proceso, desarrollo).
if os.environ.get('REDIS_URL'):
    CHANNEL_LAYERS = {'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {'hosts': [os.environ['REDIS_URL']]},
    }}
else:
    CHANNEL_LAYERS = {'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}}


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def config_mysql():
    """MySQL desde MYSQL_URL (la URL de conexión que da Railway) o desde las variables MYSQL_* sueltas."""
    if url := os.environ.get('MYSQL_URL'):
        u = urlparse(url)
        return {'NAME': u.path.lstrip('/'), 'USER': unquote(u.username or ''), 'PASSWORD': unquote(u.password or ''),
                'HOST': u.hostname, 'PORT': str(u.port or 3306)}
    if os.environ.get('MYSQL_DATABASE'):
        return {'NAME': os.environ['MYSQL_DATABASE'], 'USER': os.environ.get('MYSQL_USER', ''),
                'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''), 'HOST': os.environ.get('MYSQL_HOST', 'db'),
                'PORT': os.environ.get('MYSQL_PORT', '3306')}
    return None


if mysql := config_mysql():
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            **mysql,
            'CONN_MAX_AGE': 60,
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Destino de `manage.py collectstatic` en producción (incluye app/static/app/estilos.css).
STATIC_ROOT = BASE_DIR / 'staticfiles'
if not DEBUG:
    # Nombres con hash y archivos comprimidos: se pueden cachear para siempre en el navegador.
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }

# Detrás de un proxy con HTTPS (nginx, Caddy, Traefik, un balanceador...). En Railway siempre lo hay.
if os.environ.get('DJANGO_HTTPS', '1' if RAILWAY_PUBLIC_DOMAIN else '0') == '1':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Con EMAIL_HOST, SMTP real; sin él, los correos se imprimen en la consola (desarrollo).
# La app aún no envía correos, pero `check --deploy` exige un backend de producción.
if os.environ.get('EMAIL_HOST'):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': os.environ['EMAIL_HOST'],
                'port': int(os.environ.get('EMAIL_PORT', '587')),
                'username': os.environ.get('EMAIL_HOST_USER', ''),
                'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
                'use_tls': os.environ.get('EMAIL_USE_TLS', '1') == '1',
            },
        },
    }
else:
    MAILERS = {'default': {'BACKEND': 'django.core.mail.backends.console.EmailBackend'}}
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost')


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'perfil'
LOGOUT_REDIRECT_URL = 'login'
