# Generated by Django 6.1.2 on 2026-10-06 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('moxfield_id', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('comandante', 'Comandante'), ('principal', 'Principal'), ('banquillo', 'Banquillo')], max_length=10)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('coste', models.CharField(blank=True, max_length=100)),
                ('cmc', models.FloatField(default=0)),
                ('scryfall_id', models.CharField(max_length=36)),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='app.mazo')),
            ],
        ),
    ]
