# Generated by Django 6.1.2 on 2026-10-07 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='doble_cara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mazo',
            name='formato',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('sala', 'En sala de espera'), ('jugando', 'En juego'), ('terminada', 'Terminada')], default='sala', max_length=10)),
                ('formato', models.CharField(blank=True, max_length=40)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('juego', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptada', models.BooleanField(default=False)),
                ('mazo_nombre', models.CharField(blank=True, max_length=200)),
                ('formato', models.CharField(blank=True, max_length=40)),
                ('cartas', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='app.partida')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('partida', 'usuario'), name='jugador_unico')],
            },
        ),
    ]
