# Generated by Django 6.1.2 on 2026-10-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('de', 'a'), name='amistad_unica'), models.CheckConstraint(condition=models.Q(('de', models.F('a')), _negated=True), name='amistad_no_consigo_mismo')],
            },
        ),
    ]
